##
# Server
##
server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on_param
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /revenda-carros

##
# Spring, JPA and DataSource
##
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  ##
  # Spring Security - Resource Server
  ##
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/revenda-carros
          jwk-set-uri: http://localhost:18080/realms/revenda-carros/protocol/openid-connect/certs
      ##
      # Spring Security - OAuth2 Client
      ##
      client:
        registration:
          detran-status-veiculos:
            authorization-grant-type: client_credentials
            client-id: detran-status-veiculos-client
            client-secret: LJ30c8ZrpfNuAeWs4Lrf5huysVC0AWnD
            scope: detran:read
        provider:
          detran-status-veiculos:
            token-uri: http://localhost:18080/realms/detran/protocol/openid-connect/token

##
# OpenFeign
##
feign:
  client:
    config:
      detranClient:
        loggerLevel: full

logging:
  level:
    org.springframework.web.client: DEBUG
    br.com.zup.edu.revendacarros.carros.integrations.DetranClient: DEBUG